(assert (null? ()))
(assert !(null? 2))
(assert (pair? '(1 2)))
(assert (pair? (pair () ())))
(assert (num? 2))
(assert (num? 2.1))
(assert (num? (+ 2.1 1.3)))
(assert !(int? 2.1))
(assert !(int? 2.0))
(assert !(real? 2))
(assert (real? .2))
(assert (str? "hello"))
(assert (str? ""))
(assert !(null? ""))
; empty string has false value
(assert !"")
; zero has false value
(assert !0)
(assert !!2)
(assert !!-1)
; null has false value
(assert !())
(assert (null? ((& () ()))))
(assert (proc? (& () ())))
(assert (vec? (vec 123 4 'hello)))
(assert (vec? (vec-alloc 100)))
(def t 3)
(assert (bound? 't))
(assert (bound? 'bound?))
(assert !(bound? 'abc))

(print 'passed)
